import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="site-header">
          <div className="container" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div style={{ fontWeight: 700, color: 'var(--color-text)' }}>
              Agentic Data Quality
            </div>
            <nav className="nav">
              <Link href="/">Home</Link>
              <Link href="/upload">Upload</Link>
              <Link href="/preview">Preview</Link>
              <Link href="/results">Results</Link>
              <Link href="/insights">Insights</Link>
            </nav>
          </div>
        </header>
        <main className="main">
          <div className="container">{children}</div>
        </main>
      </body>
    </html>
  );
}
